-   id: black
    name: black
    description: 'Black: The uncompromising Python code formatter'
    entry: black
    language: python
    language_version: python3
    require_serial: true
    types: [python]

-   id: isort
    name: isort
    entry: isort
    language: python
    'types': [python]
    args: []
    additional_dependencies: []

# -   id: mypy
#     name: mypy
#     entry: mypy
#     language: python
#     'types': [python]
#     args: ["--ignore-missing-imports", "--scripts-are-modules", "--exclude experiments"]
#     require_serial: true
#     additional_dependencies: []

-   id: flake8
    name: flake8
    entry: flake8
    language: python
    'types': [python]
    additional_dependencies: []

-   id: pytest
    name: pytest
    entry: pytest
    language: python
    'types': [python]
    additional_dependencies: []